[project]
name = "extract-rename-subtitle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "escape0707", email = "tothesong@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
extract-rename-subtitle = "extract_rename_subtitle:main"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "basedpyright>=1.37.3",
    "pytest>=9.0.2",
    "ruff>=0.14.14",
]
